# Generated by Django 5.1.5 on 2025-01-22 00:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_instructor_students_remove_instructor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 21, 48, 26, 524753)),
        ),
        migrations.CreateModel(
            name='UserParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('?', "I'm weird")], max_length=1, null=True)),
                ('birth_date', models.DateTimeField(default=datetime.datetime(2025, 1, 21, 21, 48, 26, 525222))),
                ('objective', models.CharField(blank=True, max_length=100, null=True)),
                ('instructor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.instructor')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='home.userparams'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
