# Generated by Django 5.1.5 on 2025-01-22 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_instructor_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparams',
            name='user',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 21, 54, 32, 424820)),
        ),
        migrations.AlterField(
            model_name='userparams',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 21, 54, 32, 424820)),
        ),
    ]
