# Generated by Django 5.1.5 on 2025-01-22 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_userparams_name_userparams_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparams',
            name='user',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 22, 39, 41, 886612)),
        ),
        migrations.AlterField(
            model_name='userparams',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 22, 39, 41, 886612)),
        ),
    ]
