# Generated by Django 5.1.5 on 2025-01-22 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userparams_photo_alter_instructor_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 9, 20, 14, 653972)),
        ),
        migrations.AlterField(
            model_name='userparams',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 9, 20, 14, 653972)),
        ),
    ]
