# Generated by Django 5.1.5 on 2025-01-23 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_instructor_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 15, 38, 22, 230010)),
        ),
        migrations.AlterField(
            model_name='userparams',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 15, 38, 22, 230010)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True),
        ),
    ]
