# Generated by Django 5.1.5 on 2025-01-23 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_instructor_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 15, 39, 0, 973329)),
        ),
        migrations.AlterField(
            model_name='userparams',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
