# Generated by Django 5.1.5 on 2025-01-24 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_instructor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 14, 42, 52, 279773)),
        ),
    ]
