# Generated by Django 5.1.5 on 2025-01-26 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_instructor_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparams',
            name='completed_trainings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 4, 9, 145997)),
        ),
    ]
