# Generated by Django 5.1.5 on 2025-01-26 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_userparams_completed_trainings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparams',
            name='current_workout',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 6, 41, 974598)),
        ),
    ]
