# Generated by Django 5.1.5 on 2025-01-30 13:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_userparams_current_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparams',
            name='current_workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='current_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_workout', to='home.userparams'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 10, 50, 40, 949669)),
        ),
    ]
