# Generated by Django 5.1.5 on 2025-01-31 14:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_exercises_workout_alter_instructor_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparams',
            name='instructor',
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userparams'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 11, 30, 2, 378170)),
        ),
    ]
