# Generated by Django 5.1.5 on 2025-01-31 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_instructor_user_userparams_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='about',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 11, 48, 36, 180993)),
        ),
    ]
