# Generated by Django 5.1.5 on 2025-01-31 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_instructor_about_alter_instructor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='about',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 11, 53, 59, 22049)),
        ),
    ]
